export const modelConfig = [
  { name: 'id', label: 'Id', control: 'number', inputType: 'text', active: false },
  { name: 'createdAt', label: 'Létrehozva', control: 'text', inputType: 'text', active: false },
  { name: 'updatedAt', label: 'Frissítve', control: 'text', inputType: 'text', active: false },
  { name: 'modelUuid', label: 'Egyedi azonosító', control: 'text', inputType: 'text', active: false },
  { name: 'modelUploaderUid', label: 'Feltöltő aznosítója', control: 'text', inputType: 'text', active: false },
  { name: 'modelTitle', label: 'Cím', control: 'input', inputType: 'text', active: true },
  { name: 'modelDescription', label: 'Leírás', control: 'textarea', inputType: 'text', active: true },
  { name: 'modelChannel', label: 'Csatorna', control: 'select', categories: ['1', '2', '3'], inputType: 'select', active: false },
  { name: 'modelCategory', label: 'Kategória', control: 'select', categories: ['Ember', 'Állat', 'Gép', 'Egyéb'], inputType: 'select', active: true },
  { name: 'modelFormat', label: 'Formátum', control: 'input', categories: ['obj', 'fbx'], inputType: 'text', active: true },
  { name: 'modelTags', label: 'Tag-ek', control: 'input', inputType: 'text', active: true },
  { name: 'modelUrl', label: 'Modell url', control: 'file', inputType: 'text', active: true },
  { name: 'modelFileName', label: 'Fájl név', control: 'input', inputType: 'text', active: false },
  { name: 'modelImgs', label: 'Képek', control: 'file', inputType: 'text', active: true },
  { name: 'modelSourceUrl', label: 'Modell forrása', control: 'textarea', inputType: 'text', active: false },
  { name: 'modelExtraLinks', label: 'Extra linkek', control: 'textarea', inputType: 'text', active: true },
  { name: 'modelState', label: 'Állapot', categories: ['Elérhető', 'Nem elérhető'], control: 'select', inputType: 'select', active: false },
  { name: 'modelVisibility', label: 'Láthatóság', control: 'switch', inputType: 'FormCheckType ', active: true },
  { name: 'modelRigged', label: 'Riggelve', control: 'switch', inputType: 'FormCheckType ', active: true },
  { name: 'modelAnimated', label: 'Animálva', control: 'switch', inputType: 'FormCheckType ', active: true },
  { name: 'modelPolyCategory', label: 'Polygon kategória', categories: ['Alacsony', 'Közepes', 'Magas'], control: 'select', inputType: 'select', active: true },
  { name: 'modelLegality', label: 'Jogállás', categories: ['Jogtiszta modell', 'Ingyenes modell', 'Nem ismert forrás'], control: 'select', inputType: 'select', active: true }
];
