export const modelConfig = [
  { name: 'id', label: 'Id', control: 'number', inputType: 'input', isVisible: false, isRequired: false },
  { name: 'createdAt', label: 'Létrehozva', control: 'input', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'updatedAt', label: 'Frissítve', control: 'input', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelUuid', label: 'Egyedi azonosító', control: 'input', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelUploaderUid', label: 'Feltöltő aznosítója', control: 'input', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelTitle', label: 'Cím', control: 'input', inputType: 'text', isVisible: true, isRequired: true },
  { name: 'modelDescription', label: 'Leírás', control: 'textarea', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelChannel', label: 'Csatorna', control: 'select', categories: ['1', '2', '3'], inputType: 'select', isVisible: false, isRequired: false },
  { name: 'modelCategory', label: 'Kategória', control: 'select', categories: ['Ember', 'Állat', 'Gép', 'Egyéb'], inputType: 'select', isVisible: true, isRequired: false },
  { name: 'modelRenderEngine', label: 'Render engine', control: 'input', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelPolyCategory', label: 'Polygon kategória', categories: ['Alacsony', 'Közepes', 'Magas'], control: 'select', inputType: 'select', isVisible: true, isRequired: false },
  { name: 'modelPolyCount', label: 'Polygon szám', control: 'input', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelFormat', label: 'Formátum', control: 'input', categories: ['obj', 'fbx'], inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelTags', label: 'Tag-ek', control: 'input', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelUrl', label: 'Modell url', control: 'file', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelFileName', label: 'Fájl név', control: 'input', inputType: 'text', isVisible: false, isRequired: false },
  { name: 'modelImgs', label: 'Képek', control: 'file', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelSourceUrl', label: 'Modell forrása', control: 'textarea', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelIframeUrl', label: 'Iframe url', control: 'input', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelExtraLinks', label: 'Extra linkek', control: 'textarea', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelMaterialUrl', label: 'Material urls', control: 'file', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelState', label: 'Állapot', categories: ['Elérhető', 'Nem elérhető'], control: 'select', inputType: 'select', isVisible: false, isRequired: false },
  { name: 'modelVisibility', label: 'Láthatóság', control: 'switch', inputType: 'FormCheckType ', isVisible: true, isRequired: false },
  { name: 'modelRigged', label: 'Riggelve', control: 'switch', inputType: 'FormCheckType ', isVisible: true, isRequired: false },
  { name: 'modelAnimated', label: 'Animálva', control: 'switch', inputType: 'FormCheckType ', isVisible: true, isRequired: false },
  { name: 'modelUv', label: 'UV', control: 'input', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelLegality', label: 'Jogállás', categories: ['Jogtiszta modell', 'Ingyenes modell', 'Nem ismert forrás'], control: 'select', inputType: 'select', isVisible: true, isRequired: false },
  { name: 'modelScript', label: 'Script', control: 'textarea', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelDownloadedBy', label: 'Model downloaded by', control: 'input', inputType: 'text', isVisible: true, isRequired: false },
  { name: 'modelDownloadCount', label: 'Model downloaded count', control: 'input', inputType: 'text', isVisible: false, isRequired: false }
];
