import { DataTypes } from 'sequelize';

export const seqConfigForImgModels = {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  createdAt: { type: DataTypes.DATE },
  updatedAt: { type: DataTypes.DATE },
  imgUuid: { type: DataTypes.STRING },
  imgUploaderUid: { type: DataTypes.STRING },
  imgFileName: { type: DataTypes.STRING },
  imgFilePath: { type: DataTypes.STRING },
  imgFileType: { type: DataTypes.STRING },
  imgFileFormat: { type: DataTypes.STRING },
  imgFileWidth: { type: DataTypes.INTEGER },
  imgFileHeight: { type: DataTypes.INTEGER },
  imgFileResolution: { type: DataTypes.INTEGER },
  imgFileTags: { type: DataTypes.STRING },
  imgFileDescription: { type: DataTypes.STRING },
  imgFileTitle: { type: DataTypes.STRING },
  imgFileCategory: { type: DataTypes.STRING },
  imgFileSourceUrl: { type: DataTypes.STRING }
};
export const seqConfigFor3dModels = {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  createdAt: { type: DataTypes.DATE },
  updatedAt: { type: DataTypes.DATE },
  modelUuid: { type: DataTypes.STRING },
  modelUploaderUid: { type: DataTypes.STRING },
  modelTitle: { type: DataTypes.STRING },
  modelDescription: { type: DataTypes.TEXT },
  modelChannel: { type: DataTypes.STRING },
  modelCategory: { type: DataTypes.STRING },
  modelRenderEngine: { type: DataTypes.STRING },
  modelPolyCategory: { type: DataTypes.STRING },
  modelPolyCount: { type: DataTypes.STRING },
  modelFormat: { type: DataTypes.STRING },
  modelTags: { type: DataTypes.STRING },
  modelUrl: { type: DataTypes.STRING },
  modelFileName: { type: DataTypes.STRING },
  modelImgs: { type: DataTypes.STRING },
  modelSourceUrl: { type: DataTypes.STRING },
  modelIframeUrl: { type: DataTypes.STRING },
  modelExtraLinks: { type: DataTypes.TEXT },
  modelMaterialUrl: { type: DataTypes.STRING },
  modelState: { type: DataTypes.STRING },
  modelVisibility: { type: DataTypes.TINYINT },
  modelRigged: { type: DataTypes.TINYINT },
  modelAnimated: { type: DataTypes.TINYINT },
  modelUv: { type: DataTypes.STRING },
  modelLegality: { type: DataTypes.STRING },
  modelScript: { type: DataTypes.STRING },
  modelViewerUid: { type: DataTypes.STRING },
  modelViewCount: { type: DataTypes.INTEGER },
  modelDownloaderUid: { type: DataTypes.STRING },
  modelDownloadCount: { type: DataTypes.INTEGER }
};
